name: JustDetector
version: '${version}'
main: dev.meyba.justDetector.JustDetector
api-version: '1.21'
authors: [ Meyba._., Jezevcik20 ]
description: Just a detector plugin.

commands:
  justdetector:
    description: Manages detector settings
    usage: /<command> [reload|help|check <player>]
    aliases: [ detector, jd ]
permissions:
  justdetector.*:
    description: Gives access to all JustDetector commands
    default: op
    children:
      justdetector.use: true
      justdetector.reload: true
      justdetector.help: true
      justdetector.view: true
      justdetector.bypass: true
  justdetector.use:
    description: Allows use of basic detector commands
    default: op
  justdetector.reload:
    description: Allows reloading the config
    default: op
  justdetector.help:
    description: Allows a player to see the help menu
    default: true
  justdetector.view:
    description: Allows viewing detection messages
    default: op
  justdetector.bypass:
    description: Bypass kicks from detector rules
    default: op
